const SUCCESSFUL_STATUS_CODE = 200;
const CAST_OR_VALIDATION_ERROR_CODE = 400;
const UNAUTHORIZED_ERROR_CODE = 401;
const FORBIDDEN_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const CONFLICT_EMAIL_ERROR_CODE = 409;
const SERVER_ERROR_CODE = 500;
const MONGO_DUPLICATE_ERROR_CODE = 11000;

module.exports = {
  SUCCESSFUL_STATUS_CODE,
  CAST_OR_VALIDATION_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  CONFLICT_EMAIL_ERROR_CODE,
  SERVER_ERROR_CODE,
  MONGO_DUPLICATE_ERROR_CODE,
};
